# Generated by Django 3.1.7 on 2021-05-02 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtInformation',
            fields=[
                ('Art_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Art_Title', models.CharField(max_length=1000)),
                ('Description', models.TextField()),
                ('Artist', models.CharField(max_length=1000)),
                ('Completion_Date', models.DateTimeField(default=False)),
                ('Category', models.CharField(max_length=1000)),
                ('t1', models.BooleanField(default=False)),
                ('t2', models.BooleanField(default=False)),
                ('t3', models.BooleanField(default=False)),
                ('t4', models.BooleanField(default=False)),
                ('t5', models.BooleanField(default=False)),
                ('t6', models.BooleanField(default=False)),
                ('t7', models.BooleanField(default=False)),
                ('t8', models.BooleanField(default=False)),
                ('Art_Price', models.IntegerField()),
                ('pic', models.ImageField(blank=True, null=True, upload_to='Images/')),
            ],
        ),
    ]
